name: Pull Request

on:
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          cd client
          yarn install --frozen-lockfile

      - name: Run Unit Tests
        if: success()
        run: |
          cd client 
          yarn test
      
      - name: Run Build
        if: success()
        run: |
          cd client 
          yarn build
